version: '3.8'

services:
  # Food Cart API（APIサーバーのみ）
  food-cart-api:
    build:
      context: ./food-cart-demo
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./food-cart-demo:/app
      - ./food-cart-demo/mockdata:/app/mockdata
      - ./food-cart-demo/img:/app/img
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
